#!/bin/bash
KISSKIT=~/kisskit
PKGS="sdl2 SDL2_gfx SDL2_ttf SDL2_image SDL2_mixer"
CFLAGS="-Wall -Wextra -Wstrict-prototypes -g -ggdb -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -Uunix -Ulinux $(pkg-config --cflags $PKGS) -I/usr/X11R6/include -I$KISSKIT -I."
LDLIBS=
for L in $KISSKIT/basic/basic.a; do
	[ -e "$L" ] || continue
	LDLIBS="$LDLIBS $L"
done
LDLIBS="$LDLIBS -lm $(pkg-config --libs $PKGS) -lcrypt -L/usr/X11R6/lib -lX11 -lXext -lGL -lGLU -lGLEW"
C="$1" ; shift
O="${C%.*}"
${CC:-gcc} $CFLAGS $LDFLAGS -o "$O" "$C" "$@" $LDLIBS
